{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ad9a36f7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import sqlite3\n",
    "anomaly_path = '/Users/joerg/repos/development/sql/AnomalyDatabase/anomaly_database.db'\n",
    "connection = sqlite3.connect(anomaly_path)\n",
    "cursor = connection.cursor()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "d216fad9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting mariadb\n",
      "  Using cached mariadb-1.1.3.tar.gz (80 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_742eead4e8b6470482b83aa34682d559/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_742eead4e8b6470482b83aa34682d559/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-k9pyp0pd\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_742eead4e8b6470482b83aa34682d559/\n",
      "    Complete output (18 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_742eead4e8b6470482b83aa34682d559/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_742eead4e8b6470482b83aa34682d559/mariadb_posix.py\", line 63, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_742eead4e8b6470482b83aa34682d559/mariadb_posix.py\", line 28, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    \n",
      "    This error typically indicates that MariaDB Connector/C, a dependency which must be preinstalled,\n",
      "    is not found.\n",
      "    If MariaDB Connector/C is not installed, see installation instructions\n",
      "    at: https://github.com/mariadb-corporation/mariadb-connector-c/wiki/install.md.\n",
      "    If MariaDB Connector/C is installed, either set the environment variable MARIADB_CONFIG or edit\n",
      "    the configuration file 'site.cfg' to set the 'mariadb_config' option to the file location of the\n",
      "    mariadb_config utility.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/76/c0/68a69fb86d93aa21febd3c27f9aa605b39eba4674699f22c02ecc4ab65f2/mariadb-1.1.3.tar.gz#sha256=e11ad852934a242660ba0a4fa2bd2af51e053bec41962ea128ba90022ed8ad5e (from https://pypi.org/simple/mariadb/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-1.1.2.tar.gz (79 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_ab7c44ee22084c2f9eb5ca5974303dff/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_ab7c44ee22084c2f9eb5ca5974303dff/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-jqfsik6a\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_ab7c44ee22084c2f9eb5ca5974303dff/\n",
      "    Complete output (18 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_ab7c44ee22084c2f9eb5ca5974303dff/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_ab7c44ee22084c2f9eb5ca5974303dff/mariadb_posix.py\", line 63, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_ab7c44ee22084c2f9eb5ca5974303dff/mariadb_posix.py\", line 28, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    \n",
      "    This error typically indicates that MariaDB Connector/C, a dependency which must be preinstalled,\n",
      "    is not found.\n",
      "    If MariaDB Connector/C is not installed, see installation instructions\n",
      "    at: https://github.com/mariadb-corporation/mariadb-connector-c/wiki/install.md.\n",
      "    If MariaDB Connector/C is installed, either set the environment variable MARIADB_CONFIG or edit\n",
      "    the configuration file 'site.cfg' to set the 'mariadb_config' option to the file location of the\n",
      "    mariadb_config utility.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/59/46/a8ccc82fdc3de0ef5a6b31e9678fbc9301cb460957e2c94c1d02fd2c4ea4/mariadb-1.1.2.tar.gz#sha256=e1ed6b9bbd3051a9666f9b882f6f71b26f16c2acabcbd0db6c5cb5fff5d2100a (from https://pypi.org/simple/mariadb/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-1.0.11.zip (85 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_6c6b39d587024e598d34635482ffe804/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_6c6b39d587024e598d34635482ffe804/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-lang9cqe\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_6c6b39d587024e598d34635482ffe804/\n",
      "    Complete output (17 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_6c6b39d587024e598d34635482ffe804/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_6c6b39d587024e598d34635482ffe804/mariadb_posix.py\", line 59, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_6c6b39d587024e598d34635482ffe804/mariadb_posix.py\", line 28, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    \n",
      "    Please make sure, that MariaDB Connector/C is installed on your system.\n",
      "    Either set the environment variable MARIADB_CONFIG or edit the configuration\n",
      "    file 'site.cfg' and set the 'mariadb_config option, which should point\n",
      "    to the mariadb_config utility.\n",
      "    The MariaDB Download website at <https://downloads.mariadb.com/Connectors/c/>\n",
      "    provides latest stable releease of Connector/C.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/37/0a/ce5724f852f2937c6955bcea09659aa2d85d487df1c9de6711344b71527d/mariadb-1.0.11.zip#sha256=76916c892bc936c5b0f36e25a1411f651a7b7ce978992ae3a8de7e283efdacbf (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-1.0.10.zip (85 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_9fed0b8cae0b4dc6890022fe0e2b7e80/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_9fed0b8cae0b4dc6890022fe0e2b7e80/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-l4f5afa9\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_9fed0b8cae0b4dc6890022fe0e2b7e80/\n",
      "    Complete output (17 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_9fed0b8cae0b4dc6890022fe0e2b7e80/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_9fed0b8cae0b4dc6890022fe0e2b7e80/mariadb_posix.py\", line 59, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_9fed0b8cae0b4dc6890022fe0e2b7e80/mariadb_posix.py\", line 28, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    \n",
      "    Please make sure, that MariaDB Connector/C is installed on your system.\n",
      "    Either set the environment variable MARIADB_CONFIG or edit the configuration\n",
      "    file 'site.cfg' and set the 'mariadb_config option, which should point\n",
      "    to the mariadb_config utility.\n",
      "    The MariaDB Download website at <https://downloads.mariadb.com/Connectors/c/>\n",
      "    provides latest stable releease of Connector/C.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/fa/3e/406aab309101bb61cfc6745badfa3ec6c4c6f026f76b2428f597e73f7975/mariadb-1.0.10.zip#sha256=79028ba6051173dad1ad0be7518389cab70239f92b4ff8b8813dae55c3f2c53d (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  Using cached mariadb-1.0.9.zip (85 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0ff06357e6af405bb80a4d4427682022/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0ff06357e6af405bb80a4d4427682022/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-90eetx8m\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0ff06357e6af405bb80a4d4427682022/\n",
      "    Complete output (17 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0ff06357e6af405bb80a4d4427682022/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0ff06357e6af405bb80a4d4427682022/mariadb_posix.py\", line 59, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0ff06357e6af405bb80a4d4427682022/mariadb_posix.py\", line 28, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    \n",
      "    Please make sure, that MariaDB Connector/C is installed on your system.\n",
      "    Either set the environment variable MARIADB_CONFIG or edit the configuration\n",
      "    file 'site.cfg' and set the 'mariadb_config option, which should point\n",
      "    to the mariadb_config utility.\n",
      "    The MariaDB Download website at <https://downloads.mariadb.com/Connectors/c/>\n",
      "    provides latest stable releease of Connector/C.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/e4/b0/0fa0bf67c347464e04c970e406e6d4b0eea0b76c9aff6111c85708950cfc/mariadb-1.0.9.zip#sha256=02a9b3d0a076e9a0d0ea1c48b45ed09b6475e2b6a4e8c81ed9f1e82caf3bfc29 (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-1.0.8.zip (85 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_47ff657bc28845439e418f079e63929c/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_47ff657bc28845439e418f079e63929c/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-uyfjvi4m\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_47ff657bc28845439e418f079e63929c/\n",
      "    Complete output (17 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_47ff657bc28845439e418f079e63929c/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_47ff657bc28845439e418f079e63929c/mariadb_posix.py\", line 59, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_47ff657bc28845439e418f079e63929c/mariadb_posix.py\", line 28, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    \n",
      "    Please make sure, that MariaDB Connector/C is installed on your system.\n",
      "    Either set the environment variable MARIADB_CONFIG or edit the configuration\n",
      "    file 'site.cfg' and set the 'mariadb_config option, which should point\n",
      "    to the mariadb_config utility.\n",
      "    The MariaDB Download website at <https://downloads.mariadb.com/Connectors/c/>\n",
      "    provides latest stable releease of Connector/C.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/e5/30/e80702b8e9eecaddfb510a34d16dec0150d0661b07bb49fd6f55fa18781f/mariadb-1.0.8.zip#sha256=4b7b1b307a30a3cb12272d9b1dca0d13b66bd3d415b4aceb0a407f0983f341a3 (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-1.0.7.tar.gz (67 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_c226ebd546b84eb0b007aa53534d9a5b/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_c226ebd546b84eb0b007aa53534d9a5b/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-1jientxk\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_c226ebd546b84eb0b007aa53534d9a5b/\n",
      "    Complete output (17 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_c226ebd546b84eb0b007aa53534d9a5b/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_c226ebd546b84eb0b007aa53534d9a5b/mariadb_posix.py\", line 59, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_c226ebd546b84eb0b007aa53534d9a5b/mariadb_posix.py\", line 28, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    \n",
      "    Please make sure, that MariaDB Connector/C is installed on your system.\n",
      "    Either set the environment variable MARIADB_CONFIG or edit the configuration\n",
      "    file 'site.cfg' and set the 'mariadb_config option, which should point\n",
      "    to the mariadb_config utility.\n",
      "    The MariaDB Download website at <https://downloads.mariadb.com/Connectors/c/>\n",
      "    provides latest stable releease of Connector/C.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/4e/6d/0c9bf9668da4e86417f73573353d3659d222ef76a93ce1717fb33284cdea/mariadb-1.0.7.tar.gz#sha256=3c7eebcb94588b879069a00ae3894ef404f24ed350c40d633ccb98964bc1de55 (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-1.0.6.tar.gz (67 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_7c137f6c9e0445ac8975ca678c010613/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_7c137f6c9e0445ac8975ca678c010613/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-4g9i3a0y\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_7c137f6c9e0445ac8975ca678c010613/\n",
      "    Complete output (17 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_7c137f6c9e0445ac8975ca678c010613/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_7c137f6c9e0445ac8975ca678c010613/mariadb_posix.py\", line 59, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_7c137f6c9e0445ac8975ca678c010613/mariadb_posix.py\", line 28, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    \n",
      "    Please make sure, that MariaDB Connector/C is installed on your system.\n",
      "    Either set the environment variable MARIADB_CONFIG or edit the configuration\n",
      "    file 'site.cfg' and set the 'mariadb_config option, which should point\n",
      "    to the mariadb_config utility.\n",
      "    The MariaDB Download website at <https://downloads.mariadb.com/Connectors/c/>\n",
      "    provides latest stable releease of Connector/C.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/4a/db/702321e2144ba88a4803591e855f64cafad821c0adb783934b74536d7609/mariadb-1.0.6.tar.gz#sha256=aeb692f0748e22a5aa7a15c30a2921a57de940008b3937a56840d3c2db257e1b (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-1.0.5.tar.gz (67 kB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_28a708e96d4640e797e51873ebca9b10/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_28a708e96d4640e797e51873ebca9b10/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-u_62lkwg\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_28a708e96d4640e797e51873ebca9b10/\n",
      "    Complete output (17 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_28a708e96d4640e797e51873ebca9b10/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_28a708e96d4640e797e51873ebca9b10/mariadb_posix.py\", line 59, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_28a708e96d4640e797e51873ebca9b10/mariadb_posix.py\", line 28, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    \n",
      "    Please make sure, that MariaDB Connector/C is installed on your system.\n",
      "    Either set the environment variable MARIADB_CONFIG or edit the configuration\n",
      "    file 'site.cfg' and set the 'mariadb_config option, which should point\n",
      "    to the mariadb_config utility.\n",
      "    The MariaDB Download website at <https://downloads.mariadb.com/Connectors/c/>\n",
      "    provides latest stable releease of Connector/C.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ea/a2/b15b7aa791f525e5adbd27a0f3cad3c287b1566c4abd78a214b9f2f7dd7a/mariadb-1.0.5.tar.gz#sha256=e639f98a881e9b25e446c564a8e52c6ef0bcf7abcf7d5a6749bc7ef5d36e504d (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-1.0.4.tar.gz (66 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_708d80e3e5eb433b91b1ee5bdcde4e0f/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_708d80e3e5eb433b91b1ee5bdcde4e0f/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-brtz1la_\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_708d80e3e5eb433b91b1ee5bdcde4e0f/\n",
      "    Complete output (17 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_708d80e3e5eb433b91b1ee5bdcde4e0f/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_708d80e3e5eb433b91b1ee5bdcde4e0f/mariadb_posix.py\", line 59, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_708d80e3e5eb433b91b1ee5bdcde4e0f/mariadb_posix.py\", line 28, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    \n",
      "    Please make sure, that MariaDB Connector/C is installed on your system.\n",
      "    Either set the environment variable MARIADB_CONFIG or edit the configuration\n",
      "    file 'site.cfg' and set the 'mariadb_config option, which should point\n",
      "    to the mariadb_config utility.\n",
      "    The MariaDB Download website at <https://downloads.mariadb.com/Connectors/c/>\n",
      "    provides latest stable releease of Connector/C.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f5/c5/a932f8c81f8605abc737f5d097fecb5e314040e69305dc9379d3aad35f09/mariadb-1.0.4.tar.gz#sha256=0f5ab2fd83aa5996f0c6bc1ccbcaf80de3aa6eb28ca20a8ba3c670593de4d71a (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-1.0.3.tar.gz (66 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_55d337e63943470b810ff8dbeb6bfad9/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_55d337e63943470b810ff8dbeb6bfad9/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-mkfkn_gh\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_55d337e63943470b810ff8dbeb6bfad9/\n",
      "    Complete output (17 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_55d337e63943470b810ff8dbeb6bfad9/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_55d337e63943470b810ff8dbeb6bfad9/mariadb_posix.py\", line 59, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_55d337e63943470b810ff8dbeb6bfad9/mariadb_posix.py\", line 28, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    \n",
      "    Please make sure, that MariaDB Connector/C is installed on your system.\n",
      "    Either set the environment variable MARIADB_CONFIG or edit the configuration\n",
      "    file 'site.cfg' and set the 'mariadb_config option, which should point\n",
      "    to the mariadb_config utility.\n",
      "    The MariaDB Download website at <https://downloads.mariadb.com/Connectors/c/>\n",
      "    provides latest stable releease of Connector/C.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ea/72/de31a4a6bd847fdfe8b1f28d2615ea3062b836fe3367f703c91bd89580af/mariadb-1.0.3.tar.gz#sha256=72ecc86515986d9023b1fe77d12bc6f394efba502153b3271b1ba27c463efb56 (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-1.0.2.tar.gz (65 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_5858715bbf3d4947860f04580320a0f6/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_5858715bbf3d4947860f04580320a0f6/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-m1q4mjkz\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_5858715bbf3d4947860f04580320a0f6/\n",
      "    Complete output (17 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_5858715bbf3d4947860f04580320a0f6/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_5858715bbf3d4947860f04580320a0f6/mariadb_posix.py\", line 59, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_5858715bbf3d4947860f04580320a0f6/mariadb_posix.py\", line 28, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    \n",
      "    Please make sure, that MariaDB Connector/C is installed on your system.\n",
      "    Either set the environment variable MARIADB_CONFIG or edit the configuration\n",
      "    file 'site.cfg' and set the 'mariadb_config option, which should point\n",
      "    to the mariadb_config utility.\n",
      "    The MariaDB Download website at <https://downloads.mariadb.com/Connectors/c/>\n",
      "    provides latest stable releease of Connector/C.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/30/87/76711e376b8e84e293dac5fd42d6fdd44739630aac339c46ea5b234485b6/mariadb-1.0.2.tar.gz#sha256=fe975cb43105bf18751a40cf2f7a3008436dfb871e2f200e8eba78139afe222f (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-1.0.1.tar.gz (65 kB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0bf5cf8ba7a64b7b95d7e75245ef6e8b/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0bf5cf8ba7a64b7b95d7e75245ef6e8b/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-or5bpjuf\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0bf5cf8ba7a64b7b95d7e75245ef6e8b/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0bf5cf8ba7a64b7b95d7e75245ef6e8b/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0bf5cf8ba7a64b7b95d7e75245ef6e8b/mariadb_posix.py\", line 51, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0bf5cf8ba7a64b7b95d7e75245ef6e8b/mariadb_posix.py\", line 28, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    Please make sure, that MariaDB Connector/C is installed on your system, edit the configuration file 'site.cfg' and set the 'mariadb_config'\n",
      "    option, which should point to the mariadb_config utility.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/15/73/250a30543f9987af2e3f7856f29917fa22580cd6b457b8e2df0d6d80b3f3/mariadb-1.0.1.tar.gz#sha256=c80ddede70efa11d34fe8a5bb59774d8c431926e4a2f7b66c7bf55611229d857 (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-1.0.0.tar.gz (78 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_8f938ef08c4c4fd0aac7e3833d88e900/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_8f938ef08c4c4fd0aac7e3833d88e900/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-ydoefg6g\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_8f938ef08c4c4fd0aac7e3833d88e900/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_8f938ef08c4c4fd0aac7e3833d88e900/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_8f938ef08c4c4fd0aac7e3833d88e900/mariadb_posix.py\", line 49, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_8f938ef08c4c4fd0aac7e3833d88e900/mariadb_posix.py\", line 26, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    Please make sure, that MariaDB Connector/C is installed on your system, edit the configuration file 'site.cfg' and set the 'mariadb_config'\n",
      "    option, which should point to the mariadb_config utility.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/8f/c9/7050899dc1066409a17e1147d3afe1b078e582afdb755c6d3cb9c9a5c3ab/mariadb-1.0.0.tar.gz#sha256=3feeea1e103acb60dacce7d828236e5f20b334dc04b571847d80823d37671db3 (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-0.9.59.tar.gz (79 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_fd9781734f474053903dd3c3cd38555a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_fd9781734f474053903dd3c3cd38555a/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-xkj9b2hb\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_fd9781734f474053903dd3c3cd38555a/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_fd9781734f474053903dd3c3cd38555a/setup.py\", line 26, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_fd9781734f474053903dd3c3cd38555a/mariadb_posix.py\", line 49, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_fd9781734f474053903dd3c3cd38555a/mariadb_posix.py\", line 26, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    Please make sure, that MariaDB Connector/C is installed on your system, edit the configuration file 'site.cfg' and set the 'mariadb_config'\n",
      "    option, which should point to the mariadb_config utility.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ca/55/872c5b1fb3d00c0f690011d3e62d8c27e2be043e6b8efae5636620dee2e6/mariadb-0.9.59.tar.gz#sha256=7a952b9a29e37757976afe791f067fef21ebcbd416a486b8d77ab29da0b16172 (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-0.9.58.tar.gz (79 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_4faef9de4be94a60afd000653273adb6/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_4faef9de4be94a60afd000653273adb6/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-rtz79oeg\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_4faef9de4be94a60afd000653273adb6/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_4faef9de4be94a60afd000653273adb6/setup.py\", line 24, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_4faef9de4be94a60afd000653273adb6/mariadb_posix.py\", line 49, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_4faef9de4be94a60afd000653273adb6/mariadb_posix.py\", line 26, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    Please make sure, that MariaDB Connector/C is installed on your system, edit the configuration file 'site.cfg' and set the 'mariadb_config'\n",
      "    option, which should point to the mariadb_config utility.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/1e/18/f3ecade20a1bb45ace7b002b98ff8d46a72aa7895301ebf3d69ddccb7806/mariadb-0.9.58.tar.gz#sha256=4c3c8adc3957242f196fb040d24feb99b544caa85ae262e5d911b4a5444de6a7 (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-0.9.57.tar.gz (76 kB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_658d7049ea264822bf4fe27955c87ca7/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_658d7049ea264822bf4fe27955c87ca7/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-79d6acgn\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_658d7049ea264822bf4fe27955c87ca7/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_658d7049ea264822bf4fe27955c87ca7/setup.py\", line 24, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_658d7049ea264822bf4fe27955c87ca7/mariadb_posix.py\", line 49, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_658d7049ea264822bf4fe27955c87ca7/mariadb_posix.py\", line 26, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    Please make sure, that MariaDB Connector/C is installed on your system, edit the configuration file 'site.cfg' and set the 'mariadb_config'\n",
      "    option, which should point to the mariadb_config utility.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/8b/0a/f1691cd95ab780fabcc891ceb71a64a101d18aadb8cf07a86ef9eb9f823c/mariadb-0.9.57.tar.gz#sha256=e5b33d95121eef76137219ce02478b1ba06e900f055cf7dde7c748c53c5ff377 (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-0.9.56.tar.gz (76 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_c8f792dbf09445158f4512c513e5c164/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_c8f792dbf09445158f4512c513e5c164/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-su9gsn2y\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_c8f792dbf09445158f4512c513e5c164/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_c8f792dbf09445158f4512c513e5c164/setup.py\", line 24, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_c8f792dbf09445158f4512c513e5c164/mariadb_posix.py\", line 49, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_c8f792dbf09445158f4512c513e5c164/mariadb_posix.py\", line 26, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    Please make sure, that MariaDB Connector/C is installed on your system, edit the configuration file 'site.cfg' and set the 'mariadb_config'\n",
      "    option, which should point to the mariadb_config utility.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ba/8a/8a8db9b28afe901c51c171ef96bee7706c8875152a81974201b77a0a5e9e/mariadb-0.9.56.tar.gz#sha256=c66777108b94c3b4645b97bee25d557871bf0285531db2ae31788c8248bd52b9 (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-0.9.55.tar.gz (76 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0b6c9ba42703478f8c1c31374ea255dd/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0b6c9ba42703478f8c1c31374ea255dd/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-7gzzusfm\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0b6c9ba42703478f8c1c31374ea255dd/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0b6c9ba42703478f8c1c31374ea255dd/setup.py\", line 24, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0b6c9ba42703478f8c1c31374ea255dd/mariadb_posix.py\", line 49, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_0b6c9ba42703478f8c1c31374ea255dd/mariadb_posix.py\", line 26, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    Please make sure, that MariaDB Connector/C is installed on your system, edit the configuration file 'site.cfg' and set the 'mariadb_config'\n",
      "    option, which should point to the mariadb_config utility.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/7d/58/9277c227669bae5c3605eea5a1f136f199188b4b7be4b4e2a96f96c84877/mariadb-0.9.55.tar.gz#sha256=c3e2d1d7b8eb975e64242fc0ebf4b0cfe096cd3df5e94c82894f4d53dfce7913 (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-0.9.54.tar.gz (72 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_7b6a4b31963848ab8b68d2255632590b/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_7b6a4b31963848ab8b68d2255632590b/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-nsj4l3rw\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_7b6a4b31963848ab8b68d2255632590b/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_7b6a4b31963848ab8b68d2255632590b/setup.py\", line 24, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_7b6a4b31963848ab8b68d2255632590b/mariadb_posix.py\", line 49, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_7b6a4b31963848ab8b68d2255632590b/mariadb_posix.py\", line 26, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    Please make sure, that MariaDB Connector/C is installed on your system, edit the configuration file 'site.cfg' and set the 'mariadb_config'\n",
      "    option, which should point to the mariadb_config utility.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/99/16/d6cc180f0075ae486903003c201d7eab183caa4bdba3faec20d63c3d69e9/mariadb-0.9.54.tar.gz#sha256=2e8706f0d8f4024cf94a1255130090100ca74a44c85d4d801b227f10bfc56a86 (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-0.9.53.tar.gz (70 kB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_cd59f609fdc64193b9021f620ef7527a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_cd59f609fdc64193b9021f620ef7527a/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-yfhjz5ph\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_cd59f609fdc64193b9021f620ef7527a/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_cd59f609fdc64193b9021f620ef7527a/setup.py\", line 24, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_cd59f609fdc64193b9021f620ef7527a/mariadb_posix.py\", line 49, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_cd59f609fdc64193b9021f620ef7527a/mariadb_posix.py\", line 26, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    Please make sure, that MariaDB Connector/C is installed on your system, edit the configuration file 'site.cfg' and set the 'mariadb_config'\n",
      "    option, which should point to the mariadb_config utility.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/94/df/1c0d68f2f24b987b2ecb6d46175132b29da15d60a6c51bc65d4de3bf2f9c/mariadb-0.9.53.tar.gz#sha256=6cefbb3be85b932a491025c4ccfa9024cc98947426fbff6b48129e8142ee9de9 (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached mariadb-0.9.52.tar.gz (72 kB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/joerg/opt/anaconda3/envs/python38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_a03817eb476f4222a839f0ac88eeeadc/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_a03817eb476f4222a839f0ac88eeeadc/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-pip-egg-info-45e8pjq0\n",
      "         cwd: /private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_a03817eb476f4222a839f0ac88eeeadc/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_a03817eb476f4222a839f0ac88eeeadc/setup.py\", line 24, in <module>\n",
      "        cfg = get_config(options)\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_a03817eb476f4222a839f0ac88eeeadc/mariadb_posix.py\", line 49, in get_config\n",
      "        cc_version = mariadb_config(config_prg, \"cc_version\")\n",
      "      File \"/private/var/folders/z2/_gyyb63x4pv6zvl1bd53ryg00000gn/T/pip-install-2gp4disf/mariadb_a03817eb476f4222a839f0ac88eeeadc/mariadb_posix.py\", line 26, in mariadb_config\n",
      "        raise EnvironmentError(\n",
      "    OSError: mariadb_config not found.\n",
      "    Please make sure, that MariaDB Connector/C is installed on your system, edit the configuration file 'site.cfg' and set the 'mariadb_config'\n",
      "    option, which should point to the mariadb_config utility.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/d9/70/d5048fa20d2cd986181094cc35ccae284f36e80fe61e2821b79d281b03a2/mariadb-0.9.52.tar.gz#sha256=554e7067ea68430fb7c3b4df1be7c9f2ff3ab7bf806c2d9076f959645e7a96de (from https://pypi.org/simple/mariadb/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31mERROR: Could not find a version that satisfies the requirement mariadb\u001b[0m\n",
      "\u001b[31mERROR: No matching distribution found for mariadb\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "435d76f4",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'mariadb'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Input \u001b[0;32mIn [7]\u001b[0m, in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mmariadb\u001b[39;00m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'mariadb'"
     ]
    }
   ],
   "source": [
    "import mariadb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b946e748",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas.io.sql\n",
    "from sqlalchemy import create_engine"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e205bda3",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'MySQLdb'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Input \u001b[0;32mIn [2]\u001b[0m, in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0m engine \u001b[38;5;241m=\u001b[39m \u001b[43mcreate_engine\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mmariadb:///?User=db_user&;Password=pax123&Database=werderdb&Server=192.168.178.48&Port=3306\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m<string>:2\u001b[0m, in \u001b[0;36mcreate_engine\u001b[0;34m(url, **kwargs)\u001b[0m\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py:309\u001b[0m, in \u001b[0;36mdeprecated_params.<locals>.decorate.<locals>.warned\u001b[0;34m(fn, *args, **kwargs)\u001b[0m\n\u001b[1;32m    302\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m m \u001b[38;5;129;01min\u001b[39;00m kwargs:\n\u001b[1;32m    303\u001b[0m         _warn_with_version(\n\u001b[1;32m    304\u001b[0m             messages[m],\n\u001b[1;32m    305\u001b[0m             versions[m],\n\u001b[1;32m    306\u001b[0m             version_warnings[m],\n\u001b[1;32m    307\u001b[0m             stacklevel\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m3\u001b[39m,\n\u001b[1;32m    308\u001b[0m         )\n\u001b[0;32m--> 309\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/sqlalchemy/engine/create.py:560\u001b[0m, in \u001b[0;36mcreate_engine\u001b[0;34m(url, **kwargs)\u001b[0m\n\u001b[1;32m    558\u001b[0m         \u001b[38;5;28;01mif\u001b[39;00m k \u001b[38;5;129;01min\u001b[39;00m kwargs:\n\u001b[1;32m    559\u001b[0m             dbapi_args[k] \u001b[38;5;241m=\u001b[39m pop_kwarg(k)\n\u001b[0;32m--> 560\u001b[0m     dbapi \u001b[38;5;241m=\u001b[39m \u001b[43mdialect_cls\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdbapi\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mdbapi_args\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    562\u001b[0m dialect_args[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mdbapi\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;241m=\u001b[39m dbapi\n\u001b[1;32m    564\u001b[0m dialect_args\u001b[38;5;241m.\u001b[39msetdefault(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcompiler_linting\u001b[39m\u001b[38;5;124m\"\u001b[39m, compiler\u001b[38;5;241m.\u001b[39mNO_LINTING)\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:163\u001b[0m, in \u001b[0;36mMySQLDialect_mysqldb.dbapi\u001b[0;34m(cls)\u001b[0m\n\u001b[1;32m    161\u001b[0m \u001b[38;5;129m@classmethod\u001b[39m\n\u001b[1;32m    162\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mdbapi\u001b[39m(\u001b[38;5;28mcls\u001b[39m):\n\u001b[0;32m--> 163\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43m__import__\u001b[39;49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mMySQLdb\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'MySQLdb'"
     ]
    }
   ],
   "source": [
    "engine = create_engine(\"mariadb:///?User=db_user&;Password=pax123&Database=werderdb&Server=192.168.178.48&Port=3306\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2a009799",
   "metadata": {},
   "outputs": [],
   "source": [
    "server = \"192.168.178.48:3306\""
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "python38",
   "language": "python",
   "name": "python38"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
